[package]
name = "poolx-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poolx = { path = "../poolx" }
tokio = { version = "1.36.0", features = ["full"] }
